default:
  adapter: mysql2
  database: cats_rescue
  username: meowington
  password: meowguys
  host: localhost
development:
  adapter: mysql2
  database: cats_rescue
  username: meowington
  password: meowguys
  host: localhost
production:
  adapter: mysql2
  database: cats_rescue
  username: meowington
  password: meowguys
  host: localhost
