default:
  adapter: mysql2
  # database: cats_rescue
  database: project3
  username: life
  password: life
  host: localhost
development:
  adapter: mysql2
  database: project3
  username: life
  password: life
  # database: cats_rescue
  # username: meowington
  # password: meowguys
  host: localhost
production:
  adapter: mysql2
  database: project3
  username: life
  password: life
  # database: cats_rescue
  # username: meowington
  # password: meowguys
  host: localhost
